pipeline {
    agent { label 'MSBUILD22' }
    options {
        buildDiscarder(logRotator(numToKeepStr: '05'))
    }
    environment {
        MY_VARIABLE = 'This is Tims Variable'

        DEPLOY_PATH = "${WORKSPACE}\\Deploy\\"
    }
    
    stages {
        stage('Intro') {
            environment {
                STAGE_1_VARIABLE = 'Hello Stage 1!'

            }
            parallel {
                stage('step-1') {
                    steps {
                        echo "dotNet Info" 
                        echo "==========="
                        bat 'dotnet --version'
                        bat 'dotnet --list-sdks'
                    }
                }
                stage('step-2') {
                    steps {
                        echo "In stage First, step-2"
                    }
                }
            }
        }
        stage('Build') {
            steps {
                echo "Build Starting..."

                // bat "dir"
                // bat "cd SimpleAPI"
                // bat "dir"

                bat "dotnet build -o=${DEPLOY_PATH}"

                // bat "dir"

                 echo "Build Finished!"
            }
        }

        stage('Artifacts') {
            steps {
                echo "Creating Artifacts..."

                echo "Deploy Path: ${DEPLOY_PATH}" 
                echo "Workspace: ${WORKSPACE}"

                //bat "dir"

                zip zipFile: "Tim.zip", archive: false, dir: "${DEPLOY_PATH}"

                bat "dotnet publish -o=${DEPLOY_PATH}"
                //archiveArtifacts('Deploy/')
                archiveArtifacts('Tim.zip')

                bat "dir"

                echo "Artifacts Created!"
            }
        }
    }
}
