pipeline {
    agent { label 'MSBUILD22' }
    options {
        buildDiscarder(logRotator(numToKeepStr: '05'))
    }
    environment {
        VERSION = getVersionNumber()
        //VERSION = '0.0.1'
        VERSION_SUFFIX = '3'

        DEPLOY_PATH = "${WORKSPACE}\\Deploy\\"
    }
    
    stages {
        stage('Tool Info') {
            steps {
                auditTools()
                bat 'echo Path:' 
                bat 'echo %PATH%'
                bat 'echo Path2:'
                bat 'echo env.PATH'
            }
        }
        stage('Build') {
            steps {
                echo "Build Starting..."

                // bat "dir"
                // bat "cd SimpleAPI"
                // bat "dir"

                bat "dotnet build -p:VersionPrefix=${VERSION} --version-suffix ${VERSION_SUFFIX} -o=${DEPLOY_PATH}"

                // bat "dir"

                 echo "Build Finished!"
            }
        }

        stage('Artifacts') {
            steps {
                echo "Creating Artifacts..."

                echo "Deploy Path: ${DEPLOY_PATH}" 
                echo "Workspace: ${WORKSPACE}"

                //bat "dir"

                bat "dotnet publish -p:VersionPrefix=${VERSION} --version-suffix ${VERSION_SUFFIX}"
                archiveArtifacts('Deploy/')

                //zip zipFile: "Tim.zip", archive: false, dir:"${DEPLOY_PATH}"
                //echo "Zip worked"
                //archiveArtifacts artifacts: "Tim.zip", fingerprint: true 

                bat "dir"

                echo "Artifacts Created!"
            }
        }
    }
}

void auditTools() {
    //bat "git version"
    bat "dotnet --list-sdks"
    //bat "docker version"
    bat "dotnet --list-runtimes "
}

String getVersionNumber() {
    return "0.1.7"
}